### PR TITLE
Empty Users

### LINKED ISSUE #59: Fix broken token

### LINKED ISSUE #114: Create an empty user if there's no user

### PR DESCRIPTION
**Pull request by AdirYad**
close #114
close #59

### CODE REVIEW

**Comment by AdirYad** [comment]
can be empty*

File: app/Http/Controllers/AuthController.php [hunk 1]
```diff
@@ -14,11 +14,23 @@ public function register(RegisterRequest $request)
...
     $payload['password'] = bcrypt($payload['password']);
 
-    $user = User::create($payload);
+    $isLeadLoggedIn = auth()->check() && ! auth()->user()->email;
+
+    $user = $isLeadLoggedIn ? auth()->user() : User::create($payload);
+
+    if ($isLeadLoggedIn) {
+      $user->update($payload);
+      $user->refresh();
```
Comment (MatanYadaev) [inline app/Http/Controllers/AuthController.php:23]: Why `refresh`?

File: app/Http/Controllers/AuthController.php [hunk 2]
```diff
@@ -14,11 +14,23 @@ public function register(RegisterRequest $request)
...
+    }
 
     $user->notify(new VerifyUserNotification);
   }
 
+  public function registerLead()
```
Comment (MatanYadaev) [inline app/Http/Controllers/AuthController.php:29]: It's incorrect to call an empty/guest user a "lead". Lead means a user that you need to sell him something.

In this case, you should just call it "guest" - `guestRegister`

File: database/migrations/2020_10_06_201510_change_columns_to_nullable_to_users.php [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+     * Reverse the migrations.
+     *
+     * @return void
+     */
+    public function down()
+    {
+        Schema::table('users', function (Blueprint $table) {
+          $table->string('first_name')->nullable(false)->change();
+          $table->string('last_name')->nullable(false)->change();
+          $table->dropUnique(['email']);
```
Comment (MatanYadaev) [inline database/migrations/2020_10_06_201510_change_columns_to_nullable_to_users.php:35]: Not `dropUnique` maybe `addUnique`

File: resources/js/store.js [hunk 4]
```diff
@@ -2,32 +2,46 @@ import Vue from "vue";
...
 Vue.use(Vuex);
 
 export default new Vuex.Store({
   state: {
-    user: localStorage.getItem("user")
-      ? JSON.parse(localStorage.getItem("user"))
-      : null,
+    user:
+      localStorage.getItem("user") &&
+      typeof localStorage.getItem("user") === "object"
```
Comment (MatanYadaev) [inline resources/js/store.js:13]: `localStorage.getItem("user")` will never be an object, it's a string. Did you test it??

File: resources/js/store.js [hunk 5]
```diff
@@ -2,32 +2,46 @@ import Vue from "vue";
...
+    isTokenCorrect(state) {
       return typeof state.token === "string";
-    }
+    },
+
+    isLoggedIn(state, getters) {
+      return getters.isTokenCorrect && state.user;
+    },
+
+    isLeadLoggedIn(state, getters) {
```
Comment (MatanYadaev) [inline resources/js/store.js:32]: `isGuestLoggedIn`

File: resources/js/store.js [hunk 6]
```diff
@@ -49,13 +63,50 @@ export default new Vuex.Store({
...
   },
 
   actions: {
+    auth({ dispatch, commit, getters }) {
+      if (!getters.isTokenCorrect) {
+        return;
+      }
+
+      return axiosInstance
+        .get("/auth")
```
Comment (MatanYadaev) [inline resources/js/store.js:76]: Call it `/me` instead of `/auth`, it will be easier to understand

File: app/Http/Controllers/AuthController.php (hunk 1 above)
Comment (AdirYad) [reply app/Http/Controllers/AuthController.php:23]: Because it didn't return the updated user so I had to refresh.

File: resources/js/store.js (hunk 4 above)
Comment (AdirYad) [reply resources/js/store.js:13]: I did and it worked

Comment (AdirYad) [reply resources/js/store.js:13]: When it was a string the statement worked as expected and when it was an object it worked.

Comment (MatanYadaev) [reply resources/js/store.js:13]: How it might be an object? `getItem` will always return `null` or a `string`

Comment (AdirYad) [reply resources/js/store.js:13]: I don't know but it worked when I checked.
I'll check it again today.

File: app/Http/Controllers/AuthController.php (hunk 1 above)
Comment (AdirYad) [reply app/Http/Controllers/AuthController.php:23]: In the end, it worked without refresh.
When I tried it yesterday it didn't work without refreshing.

File: database/migrations/2020_10_06_201510_change_columns_to_nullable_to_users.php (hunk 3 above)
Comment (AdirYad) [reply database/migrations/2020_10_06_201510_change_columns_to_nullable_to_users.php:35]: The emails are still unique even though they're null.
`
          $table->dropUnique(['email']);
          $table->string('email')->unique()->nullable()->change();
`
But reversing it will cause some bugs because it already has some null fields and it's impossible to reverse it because of it.
